### ISSUE TITLE
Skins don't work

### ISSUE THREAD

**Issue by arqbyte** [MrLetsplay2003/ShittyAuthLauncher#8]
I tried it out, I hosted the auth server as well but the skin was displayed wrong.

**Comment by MrLetsplay2003** [comment]
On what version of Minecraft did the issue occur?
Also, are you using the latest development build of the launcher?

**Comment by arqbyte** [comment]
I am using the latest development version, and it occurred on version 1.20.1.
When I clicked Play, it said patching authlib, and then I entered the game, neithr cape or skin worked.

**Comment by arqbyte** [comment]
Oh so you friends with NaysKutzu

**Comment by MrLetsplay2003** [comment]
I just tested it and I think it's a bug during the setup of the ShittyAuthServer.

Make sure that the `HTTP Base URL` is correctly configured (It should be the URL to your server, e.g. `https://my.domain` or `http://localhost:8880` with no trailing slash) in the WebinterfaceAPI settings. When I change that, it works as intended

**Comment by MrLetsplay2003** [comment]
The issue should be fixed in the newest version of the ShittyAuthServer

**Comment by arqbyte** [comment]
Alright, I will try it out.

**Comment by GreenAnemone** [comment]
I'm using the latest version of ShittyAuthServer along with the launcher and patcher, Minecraft version 1.20.2 and still having issues with skins.
The skins work but only partially, my own skin works but other users' skins don't show up. The same applies to other users, their skins show for them but can't see anybody else's.

`[22:41:48] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 501 milliseconds
[22:41:51] [Render thread/INFO]: Environment: Environment[accountsHost=http://redsie.co.uk:8880, sessionHost=http://redsie.co.uk:8880, servicesHost=http://redsie.co.uk:8880, name=PROD]
[22:41:51] [Render thread/INFO]: Setting user: greenanemone
[22:41:51] [Render thread/INFO]: Backend library: LWJGL version 3.3.2+13
[22:41:55] [Render thread/ERROR]: Error while loading the narrator
com.mojang.text2speech.Narrator$InitializeException: Failed to load library flite
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:69) ~[text2speech-1.17.9.jar:?]
	at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar:?]
	at eqn.<init>(SourceFile:19) ~[1.20.2.jar:?]
	at eqv.<init>(SourceFile:649) ~[1.20.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:214) ~[1.20.2.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'flite':
libflite.so: cannot open shared object file: No such file or directory
libflite.so: cannot open shared object file: No such file or directory
Native library (linux-x86-64/libflite.so) not found in resource path (/home/greenanemone/.minecraft-shitty/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar:/home/greenanemone/.minecraft-shitty/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar:/home/greenanemone/.minecraft-shitty/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/home/greenanemone/.minecraft-shitty/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar:/home/greenanemone/.minecraft-shitty/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar:/home/greenanemone/.minecraft-shitty/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar:/home/greenanemone/.minecraft-shitty/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar:/home/greenanemone/.minecraft-shitty/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar:/home/greenanemone/.minecraft-shitty/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar:/home/greenanemone/.minecraft-shitty/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar:/home/greenanemone/.minecraft-shitty/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar:/home/greenanemone/.minecraft-shitty/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar:/home/greenanemone/.minecraft-shitty/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar:/home/greenanemone/.minecraft-shitty/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-aarch_64.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-x86_64.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar:/home/greenanemone/.minecraft-shitty/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar:/home/greenanemone/.minecraft-shitty/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar:/home/greenanemone/.minecraft-shitty/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/home/greenanemone/.minecraft-shitty/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar:/home/greenanemone/.minecraft-shitty/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar:/home/greenanemone/.minecraft-shitty/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/home/greenanemone/.minecraft-shitty/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar:/home/greenanemone/.minecraft-shitty/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar:/home/greenanemone/.minecraft-shitty/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar:/home/greenanemone/.minecraft-shitty/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar:/home/greenanemone/.minecraft-shitty/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2-natives-linux.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2-natives-linux.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2-natives-linux.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2-natives-linux.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2-natives-linux.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2-natives-linux.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2-natives-linux.jar:/home/greenanemone/.minecraft-shitty/libraries/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar:/home/greenanemone/.minecraft-shitty/versions/1.20.2/1.20.2.jar:/home/greenanemone/.minecraft-shitty/libraries/com/mojang/authlib/5.0.47/patched/c193b291ff07b2cc19837d71d7cde80b.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:323) ~[jna-5.13.0.jar:5.13.0 (b0)]
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483) ~[jna-5.13.0.jar:5.13.0 (b0)]
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:425) ~[jna-5.13.0.jar:5.13.0 (b0)]
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.17.9.jar:?]
	... 5 more
	Suppressed: java.lang.UnsatisfiedLinkError: libflite.so: cannot open shared object file: No such file or directory
		at com.sun.jna.Native.open(Native Method) ~[jna-5.13.0.jar:5.13.0 (b0)]
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:211) ~[jna-5.13.0.jar:5.13.0 (b0)]
		at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483) ~[jna-5.13.0.jar:5.13.0 (b0)]
		at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:425) ~[jna-5.13.0.jar:5.13.0 (b0)]
		at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.17.9.jar:?]
		at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
		at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar:?]
		at eqn.<init>(SourceFile:19) ~[1.20.2.jar:?]
		at eqv.<init>(SourceFile:649) ~[1.20.2.jar:?]
		at net.minecraft.client.main.Main.main(SourceFile:214) ~[1.20.2.jar:?]
	Suppressed: java.lang.UnsatisfiedLinkError: libflite.so: cannot open shared object file: No such file or directory
		at com.sun.jna.Native.open(Native Method) ~[jna-5.13.0.jar:5.13.0 (b0)]
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:224) ~[jna-5.13.0.jar:5.13.0 (b0)]
		at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483) ~[jna-5.13.0.jar:5.13.0 (b0)]
		at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:425) ~[jna-5.13.0.jar:5.13.0 (b0)]
		at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.17.9.jar:?]
		at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
		at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar:?]
		at eqn.<init>(SourceFile:19) ~[1.20.2.jar:?]
		at eqv.<init>(SourceFile:649) ~[1.20.2.jar:?]
		at net.minecraft.client.main.Main.main(SourceFile:214) ~[1.20.2.jar:?]
	Suppressed: java.io.IOException: Native library (linux-x86-64/libflite.so) not found in resource path (/home/greenanemone/.minecraft-shitty/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar:/home/greenanemone/.minecraft-shitty/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar:/home/greenanemone/.minecraft-shitty/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/home/greenanemone/.minecraft-shitty/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar:/home/greenanemone/.minecraft-shitty/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar:/home/greenanemone/.minecraft-shitty/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar:/home/greenanemone/.minecraft-shitty/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar:/home/greenanemone/.minecraft-shitty/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar:/home/greenanemone/.minecraft-shitty/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar:/home/greenanemone/.minecraft-shitty/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar:/home/greenanemone/.minecraft-shitty/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar:/home/greenanemone/.minecraft-shitty/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar:/home/greenanemone/.minecraft-shitty/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar:/home/greenanemone/.minecraft-shitty/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-aarch_64.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-x86_64.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar:/home/greenanemone/.minecraft-shitty/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar:/home/greenanemone/.minecraft-shitty/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar:/home/greenanemone/.minecraft-shitty/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar:/home/greenanemone/.minecraft-shitty/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/home/greenanemone/.minecraft-shitty/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar:/home/greenanemone/.minecraft-shitty/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar:/home/greenanemone/.minecraft-shitty/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/home/greenanemone/.minecraft-shitty/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar:/home/greenanemone/.minecraft-shitty/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar:/home/greenanemone/.minecraft-shitty/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar:/home/greenanemone/.minecraft-shitty/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar:/home/greenanemone/.minecraft-shitty/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2-natives-linux.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2-natives-linux.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2-natives-linux.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2-natives-linux.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2-natives-linux.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2-natives-linux.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar:/home/greenanemone/.minecraft-shitty/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2-natives-linux.jar:/home/greenanemone/.minecraft-shitty/libraries/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar:/home/greenanemone/.minecraft-shitty/versions/1.20.2/1.20.2.jar:/home/greenanemone/.minecraft-shitty/libraries/com/mojang/authlib/5.0.47/patched/c193b291ff07b2cc19837d71d7cde80b.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1145) ~[jna-5.13.0.jar:5.13.0 (b0)]
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:295) ~[jna-5.13.0.jar:5.13.0 (b0)]
		at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483) ~[jna-5.13.0.jar:5.13.0 (b0)]
		at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:425) ~[jna-5.13.0.jar:5.13.0 (b0)]
		at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.17.9.jar:?]
		at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
		at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar:?]
		at eqn.<init>(SourceFile:19) ~[1.20.2.jar:?]
		at eqv.<init>(SourceFile:649) ~[1.20.2.jar:?]
		at net.minecraft.client.main.Main.main(SourceFile:214) ~[1.20.2.jar:?]
[22:41:55] [Render thread/INFO]: Reloading ResourceManager: vanilla
[22:41:56] [Worker-Main-4/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[22:42:01] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[22:42:01] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[22:42:01] [Render thread/INFO]: OpenAL initialized on device Built-in Audio Analog Stereo
[22:42:01] [Render thread/INFO]: Sound engine started
[22:42:01] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[22:42:01] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[22:42:01] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[22:42:01] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[22:42:01] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[22:42:01] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[22:42:01] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[22:42:01] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[22:42:01] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[22:42:01] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[22:42:01] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[22:42:01] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[22:42:01] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[22:42:01] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[22:42:07] [Render thread/INFO]: Connecting to 90.254.85.104, 25565
[22:42:10] [Render thread/WARN]: Ignoring chat session from RedOctoling due to missing Services public key
[22:42:10] [Render thread/WARN]: Ignoring chat session from greenanemone due to missing Services public key
[22:42:11] [Render thread/INFO]: Loaded 103 advancements
[22:42:11] [Worker-Main-5/ERROR]: Property textures has been tampered with (signature invalid)
[22:42:12] [IO-Worker-1/INFO]: Could not authorize you against Realms server: Invalid session id
[22:42:12] [IO-Worker-1/ERROR]: Couldn't connect to realms
ens: Realms authentication error with message 'Invalid session id'
	at emf.a(SourceFile:432) ~[1.20.2.jar:?]
	at emf.f(SourceFile:218) ~[1.20.2.jar:?]
	at elz.c(SourceFile:45) ~[1.20.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:42:38] [Render thread/WARN]: Received passengers for unknown entity
[22:42:38] [Worker-Main-2/ERROR]: Property textures has been tampered with (signature invalid)`

**Comment by MrLetsplay2003** [comment]
@GreenAnemone Thanks for reporting that issue, I will look into that

**Comment by MrLetsplay2003** [comment]
It seems something has changed about how profile signatures work in newer versions of Minecraft.

I've just pushed an update to the ShittyAuthServer that should fix the invalid signatures.

**Comment by MrLetsplay2003** [comment]
Closing this issue as it seems to have been resolved
